development:
  secret_token: <%= ENV['my_secret_token'] %>
  secret_key_base: <%= ENV['secret_key_base'] %>

production:
  secret_token: <%= ENV['my_secret_token'] %>
  secret_key_base: <%= ENV['secret_key_base'] %>
