development:
  secret_token: "my_secret_token"
  secret_key_base: "ijx813jduwnd7h93dhh3987hx781398h"

production:
  secret_token: <%= ENV['my_secret_token'] %>
  secret_key_base: <%= ENV['secret_key_base'] %>
